### PR TITLE
Remove -arch i386

### PR DESCRIPTION
**Pull request by jechol**
`-arch x86_64` and `-arch i386` conflicts.

### CODE REVIEW

**Comment by lloeki** [comment]
I suppose this solves the following build issue on Mojave?

```
clang -bundle -o x86_64-darwin/libscrypt_ext.bundle x86_64-darwin/crypto_scrypt.o x86_64-darwin/crypto_scrypt_smix.o x86_64-darwin/crypto_scrypt_smix_sse2.o
x86_64-darwin/insecure_memzero.o x86_64-darwin/memlimit.o x86_64-darwin/scrypt_calibrate.o x86_64-darwin/scrypt_ext.o x86_64-darwin/scryptenc_cpuperf.o x86_64-darwin/sha256.o
x86_64-darwin/warnp.o -fexceptions -arch x86_64 -arch i386
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
--- lots of missing symbols ---
```

**Comment by lloeki** [comment]
I confirm a manually built gem with the above patch and using `rake install` compiles correctly under Mojave.

Note for those who would like to do the same until this PR or something similar is merged, to build the gem locally you will need to disable signing the gem straight in `scrypt.gemspec`:

```
  #s.cert_chain  = ['certs/stakach.pem']
  #s.signing_key = File.expand_path("~/.ssh/gem-private_key.pem") if $0 =~ /gem\z/
```

**Comment by nathanjo** [comment]
Confirm this is currently broken in macOS Mojave.

**Comment by masterial** [comment]
Does not work on Mojave. Fix it please.

**Comment by johanns** [comment]
#72 Fix merged into master.

**Pull request closed without merging**
