### PR TITLE
Support Ruby 2.7

### PR DESCRIPTION
**Pull request by johanns**
#77 

Replaced `scanf` usage in `SCrypt::Engine.memory_cost` method to avoid adding a runtime dependency with the release of Ruby 2.7.

I also took the opportunity to the split main code body (`lib/scrypt.rb`) into multiple files under `scrypt` subdirectory (`engine.rb`, `errors.rb`, and `password.rb`) to improve readability. There are few instance of minor logic changes as well (replaced nested `if/else` with guard clause, etc.) -- overall, minor and low-risk. 

Obviously, all tests pass*. :)

* Rubinius tests are failing because FFI gem (1.11.2) fails to install. It seems that FFI gem itself doesn't test against Rubinius on TravisCI, even though the their README mentions support for it. I've added all Rubinius tests to "Allowed Failures" for the time being. 

I also added TruffleRuby to the test set, which seems to pass.

### CODE REVIEW

**Comment by stakach** [comment]
might have an issue with OSX actually.

**Comment by johanns** [comment]
@stakach I tested it on macOS Catalina. What issue are you seeing?

**Comment by stakach** [comment]
`/.rvm/gems/ruby-2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi/ffi.rb:89:in `find_type': cannot resolve type size_t (TypeError)`

**Comment by johanns** [comment]
I have a Mojave VM for testing -- looking into it.

**Comment by johanns** [comment]
I'm not able to reproduce. Any other clues in the backtrace?

```
Mojave:scrypt jg$ gem install bundler

Fetching: bundler-2.0.2.gem (100%)
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Installing ri documentation for bundler-2.0.2
Done installing documentation for bundler after 4 seconds
1 gem installed

Mojave:scrypt jg$ bundle install
Fetching gem metadata from http://rubygems.org/............
Resolving dependencies...
Fetching rake 12.3.3
Installing rake 12.3.3
Fetching ast 2.4.0
Installing ast 2.4.0
Fetching awesome_print 1.8.0
Installing awesome_print 1.8.0
Using bundler 2.0.2
Fetching diff-lcs 1.3
Installing diff-lcs 1.3
Fetching ffi 1.11.2
Installing ffi 1.11.2 with native extensions
Fetching ffi-compiler 1.0.1
Installing ffi-compiler 1.0.1
Fetching jaro_winkler 1.5.4
Installing jaro_winkler 1.5.4 with native extensions
Fetching parallel 1.19.0
Installing parallel 1.19.0
Fetching parser 2.6.5.0
Installing parser 2.6.5.0
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching rdoc 4.3.0
Installing rdoc 4.3.0
Fetching rspec-support 3.9.0
Installing rspec-support 3.9.0
Fetching rspec-core 3.9.0
Installing rspec-core 3.9.0
Fetching rspec-expectations 3.9.0
Installing rspec-expectations 3.9.0
Fetching rspec-mocks 3.9.0
Installing rspec-mocks 3.9.0
Fetching rspec 3.9.0
Installing rspec 3.9.0
Fetching ruby-progressbar 1.10.1
Installing ruby-progressbar 1.10.1
Fetching unicode-display_width 1.6.0
Installing unicode-display_width 1.6.0
Fetching rubocop 0.76.0
Installing rubocop 0.76.0
Fetching rubocop-gitlab-security 0.1.1
Installing rubocop-gitlab-security 0.1.1
Fetching rubocop-performance 1.5.1
Installing rubocop-performance 1.5.1
Using scrypt 3.0.7 from source at `.`
Bundle complete! 9 Gemfile dependencies, 23 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

Mojave:scrypt jg$ rake
mkdir -p ext/scrypt/x86_64-darwin
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/crypto_scrypt.o -c ext/scrypt/crypto_scrypt.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/crypto_scrypt_smix.o -c ext/scrypt/crypto_scrypt_smix.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/crypto_scrypt_smix_sse2.o -c ext/scrypt/crypto_scrypt_smix_sse2.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/insecure_memzero.o -c ext/scrypt/insecure_memzero.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/memlimit.o -c ext/scrypt/memlimit.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/scrypt_calibrate.o -c ext/scrypt/scrypt_calibrate.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/scrypt_ext.o -c ext/scrypt/scrypt_ext.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/scryptenc_cpuperf.o -c ext/scrypt/scryptenc_cpuperf.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/sha256.o -c ext/scrypt/sha256.c
clang -fexceptions -O -fno-omit-frame-pointer -fno-strict-aliasing -Wall -std=c99 -msse -msse2 -arch x86_64   -o ext/scrypt/x86_64-darwin/warnp.o -c ext/scrypt/warnp.c
clang -bundle -o ext/scrypt/x86_64-darwin/libscrypt_ext.bundle ext/scrypt/x86_64-darwin/crypto_scrypt.o ext/scrypt/x86_64-darwin/crypto_scrypt_smix.o ext/scrypt/x86_64-darwin/crypto_scrypt_smix_sse2.o ext/scrypt/x86_64-darwin/insecure_memzero.o ext/scrypt/x86_64-darwin/memlimit.o ext/scrypt/x86_64-darwin/scrypt_calibrate.o ext/scrypt/x86_64-darwin/scrypt_ext.o ext/scrypt/x86_64-darwin/scryptenc_cpuperf.o ext/scrypt/x86_64-darwin/sha256.o ext/scrypt/x86_64-darwin/warnp.o -fexceptions -arch x86_64 
/Users/jg/.rubies/ruby-2.5.1/bin/ruby -I/Users/jg/.gem/ruby/2.5.1/gems/rspec-core-3.9.0/lib:/Users/jg/.gem/ruby/2.5.1/gems/rspec-support-3.9.0/lib /Users/jg/.gem/ruby/2.5.1/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
...............................

Finished in 0.43364 seconds (files took 0.15998 seconds to load)
31 examples, 0 failures

/Users/jg/.rubies/ruby-2.5.1/bin/ruby -I/Users/jg/.gem/ruby/2.5.1/gems/rspec-core-3.9.0/lib:/Users/jg/.gem/ruby/2.5.1/gems/rspec-support-3.9.0/lib /Users/jg/.gem/ruby/2.5.1/gems/rspec-core-3.9.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
...............................

Finished in 0.31279 seconds (files took 0.15443 seconds to load)
31 examples, 0 failures
```

**Comment by stakach** [comment]
That's the clue.
`rake` works for me too

```
gem build scrypt.gemspec
gem install scrypt-3.0.7.gem
```

The install fails for me

**Comment by johanns** [comment]
Ok, that's helpful, and I see the problem now.

```
$ gem install scrypt-3.0.7.gem 
Building native extensions. This could take a while...
ERROR:  Error installing scrypt-3.0.7.gem:
	ERROR: Failed to build gem native extension.

    current directory: /Users/jg/.gem/ruby/2.5.1/gems/scrypt-3.0.7/ext/scrypt
/Users/jg/.rubies/ruby-2.5.1/bin/ruby -rrubygems /Users/jg/.gem/ruby/2.5.1/gems/rake-12.3.3/exe/rake RUBYARCHDIR=/Users/jg/.gem/ruby/2.5.1/extensions/x86_64-darwin-18/2.5.0-static/scrypt-3.0.7 RUBYLIBDIR=/Users/jg/.gem/ruby/2.5.1/extensions/x86_64-darwin-18/2.5.0-static/scrypt-3.0.7
mkdir -p x86_64-darwin
/Users/jg/.rubies/ruby-2.5.1/bin/ruby -I/Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi -I../../lib/scrypt /Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/exporter.rb ../../lib/scrypt/scrypt_ext.rb ./scrypt_ext.h
/Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi/ffi.rb:89:in `find_type': cannot resolve type size_t (TypeError)
	from /Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi/ffi.rb:202:in `find_type'
	from /Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi/ffi.rb:174:in `block in attach_function'
	from /Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi/ffi.rb:174:in `map'
	from /Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/fake_ffi/ffi.rb:174:in `attach_function'
	from /Users/jg/.gem/ruby/2.5.1/gems/scrypt-3.0.7/lib/scrypt/scrypt_ext.rb:15:in `<module:Ext>'
	from /Users/jg/.gem/ruby/2.5.1/gems/scrypt-3.0.7/lib/scrypt/scrypt_ext.rb:7:in `<module:SCrypt>'
	from /Users/jg/.gem/ruby/2.5.1/gems/scrypt-3.0.7/lib/scrypt/scrypt_ext.rb:6:in `<top (required)>'
	from /Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/exporter.rb:3:in `load'
	from /Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/exporter.rb:3:in `<main>'
rake aborted!
Command failed with status (1): [/Users/jg/.rubies/ruby-2.5.1/bin/rub...]
/Users/jg/.gem/ruby/2.5.1/gems/ffi-compiler-1.0.1/lib/ffi-compiler/compile_task.rb:160:in `block (2 levels) in define_task!'
/Users/jg/.gem/ruby/2.5.1/gems/rake-12.3.3/exe/rake:27:in `<main>'
Tasks: TOP => default => x86_64-darwin/libscrypt_ext.bundle => x86_64-darwin/crypto_scrypt.o => ./scrypt_ext.h
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/jg/.gem/ruby/2.5.1/gems/scrypt-3.0.7 for inspection.
Results logged to /Users/jg/.gem/ruby/2.5.1/extensions/x86_64-darwin-18/2.5.0-static/scrypt-3.0.7/gem_make.out
```

**Comment by johanns** [comment]
I pushed a fix to master.

**Comment by stakach** [comment]
pushed the release to Rubygems

**Pull request merged**
